// Pre-computes the hourly bus frequency at every paradero from the GTFS
// stop_times table. The output powers the "Frecuencia GTFS" block in the
// stop detail sheet.
//
// Shape:
//   STOP_FREQUENCY: Record<stopId, number[7 * 24]>
//   where `arr[day * 24 + hour]` is the number of buses scheduled to pass
//   that paradero during that hour-of-day on that day-of-week
//   (0=Monday..6=Sunday).
//
// Run: npm run sync:stop-frequency

import { writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const DEFAULT_DB =
  '/Users/marcorojasbelmar/Desktop/api red/legal_transit_backend/data/db/gran_concepcion_candidate.sqlite';
const dbPath = process.env.GTFS_DB_PATH ?? DEFAULT_DB;
const outPath = resolve('src/data/gtfs-stop-frequency.generated.ts');

function rows<T>(sql: string): T[] {
  const result = spawnSync('sqlite3', ['-json', dbPath, sql], {
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 256,
  });
  if (result.status !== 0) {
    throw new Error(result.stderr.trim() || `sqlite3 exited with ${result.status}`);
  }
  const text = result.stdout.trim();
  return text ? (JSON.parse(text) as T[]) : [];
}

interface CalendarRow {
  service_id: string | number;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
}

interface VisitRow {
  stop_id: string | number;
  service_id: string | number;
  arrival_hour: number;
}

// Map service_id → 7-bit day mask (0=mon..6=sun)
console.log('Reading calendar…');
const calendar = rows<CalendarRow>(`
  SELECT
    service_id,
    CAST(monday AS INTEGER) AS monday,
    CAST(tuesday AS INTEGER) AS tuesday,
    CAST(wednesday AS INTEGER) AS wednesday,
    CAST(thursday AS INTEGER) AS thursday,
    CAST(friday AS INTEGER) AS friday,
    CAST(saturday AS INTEGER) AS saturday,
    CAST(sunday AS INTEGER) AS sunday
  FROM calendar
`);

const serviceDays = new Map<string, boolean[]>();
for (const c of calendar) {
  serviceDays.set(String(c.service_id), [
    Boolean(c.monday),
    Boolean(c.tuesday),
    Boolean(c.wednesday),
    Boolean(c.thursday),
    Boolean(c.friday),
    Boolean(c.saturday),
    Boolean(c.sunday),
  ]);
}

// Aggregate stop_times for urban-bus trips only (route_type=3). Bucket by
// hour-of-day, accumulate per (stop_id, service_id).
console.log('Reading per-stop arrivals…');
const visits = rows<VisitRow>(`
  WITH bus_routes AS (
    SELECT route_id FROM routes WHERE CAST(route_type AS INTEGER) = 3
  ),
  bus_trips AS (
    SELECT t.trip_id, t.service_id
    FROM trips t
    JOIN bus_routes br ON br.route_id = t.route_id
  )
  SELECT
    st.stop_id,
    bt.service_id,
    CAST(SUBSTR(st.arrival_time, 1, 2) AS INTEGER) % 24 AS arrival_hour
  FROM stop_times st
  JOIN bus_trips bt ON bt.trip_id = st.trip_id;
`);
console.log(`  → ${visits.length.toLocaleString('en-US')} stop-arrivals indexed`);

// Aggregate: for each (stopId, day, hour), count visits.
const freq = new Map<string, Uint16Array>();
let unknownService = 0;
for (const v of visits) {
  const days = serviceDays.get(String(v.service_id));
  if (!days) {
    unknownService += 1;
    continue;
  }
  const stopId = `gtfs-stop-${v.stop_id}`;
  let arr = freq.get(stopId);
  if (!arr) {
    arr = new Uint16Array(7 * 24);
    freq.set(stopId, arr);
  }
  const hour = Math.max(0, Math.min(23, v.arrival_hour));
  for (let d = 0; d < 7; d++) {
    if (days[d]) arr[d * 24 + hour] += 1;
  }
}
if (unknownService > 0) console.warn(`  ! ${unknownService} arrivals with no calendar entry`);

console.log(`  → ${freq.size} paraderos with bus arrivals`);

// Emit. Compact: skip zeros at the end of each day to save bytes, but
// readability favours emitting fixed-length arrays — JSON.stringify on a
// Uint16Array fragment can't be done directly. We just spread to numbers.
const banner = `// AUTO-GENERATED by scripts/extract-stop-frequency.ts on ${new Date().toISOString()}.
// Hourly bus frequency at every paradero. Each entry is a flat 168-element
// array — \`arr[day * 24 + hour]\` is the number of buses scheduled to pass
// during that hour. Day index: 0=Monday..6=Sunday.
// Re-generate: \`npm run sync:stop-frequency\`.

`;

const sortedIds = Array.from(freq.keys()).sort();
const body = sortedIds
  .map((id) => {
    const arr = freq.get(id)!;
    // Trim trailing zeros to compact; runtime code pads when reading.
    let lastNonZero = -1;
    for (let i = 167; i >= 0; i--) {
      if (arr[i] !== 0) {
        lastNonZero = i;
        break;
      }
    }
    if (lastNonZero === -1) return null; // skip empty rows
    const slice = Array.from(arr.slice(0, lastNonZero + 1));
    return `  ${JSON.stringify(id)}: [${slice.join(',')}]`;
  })
  .filter((v) => v !== null)
  .join(',\n');

const output = `${banner}export const STOP_FREQUENCY: Record<string, number[]> = {
${body},
};

export const STOP_FREQUENCY_META = {
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  paraderos: ${freq.size},
  arrivals: ${visits.length},
} as const;
`;

writeFileSync(outPath, output);
console.log(`Wrote ${outPath} (${(output.length / 1024).toFixed(1)} KB raw)`);
