// Build-time precompute of the paradero coverage grid.
//
// For each 300 × 300 m cell over the Concepción metro bbox, computes the
// distance from the cell center to the nearest paradero in the GTFS feed.
// Cells with no paradero within 3 km are dropped (cuts ocean + rural noise).
//
// Output is a flat array of [lat, lng, distanceMeters] tuples, consumed by
// the "Cobertura territorial" layer in conce-map.
//
// Run: npm run sync:coverage

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { GTFS_STOPS } from '../src/data/gtfs-concepcion.generated.ts';

const OUT = resolve('src/data/coverage.generated.ts');

// Bbox shared with the other sync scripts — covers Coronel → Tomé.
const BBOX = {
  south: -37.10,
  north: -36.65,
  west: -73.25,
  east: -72.80,
};

// 300 m grid: 0.003° lat ≈ 333 m; at this latitude 0.003° lon ≈ 268 m. We
// pick a constant 0.003° step in both directions — slight east-west
// stretch is invisible at city zoom.
const STEP = 0.003;

// Cells farther than this from any paradero are dropped. Keeps grid focused
// on the populated area, avoiding ~10 k cells of ocean / mountain noise.
const MAX_INTERESTING_M = 3000;

// Spatial hash: bucket paraderos into ~1.1 km × 1 km tiles so each cell's
// nearest-paradero search only checks a few dozen neighbours.
const HASH_STEP = 0.01;
const hashKey = (lat: number, lng: number) =>
  `${Math.floor(lat / HASH_STEP)},${Math.floor(lng / HASH_STEP)}`;

const buckets = new Map<string, Array<{ lat: number; lng: number }>>();
for (const p of GTFS_STOPS) {
  const k = hashKey(p.lat, p.lng);
  const list = buckets.get(k) ?? [];
  list.push({ lat: p.lat, lng: p.lng });
  buckets.set(k, list);
}

const M_PER_DEG_LAT = 111_320;
function distMeters(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const dy = (aLat - bLat) * M_PER_DEG_LAT;
  const meanLat = ((aLat + bLat) / 2) * (Math.PI / 180);
  const dx = (aLng - bLng) * M_PER_DEG_LAT * Math.cos(meanLat);
  return Math.sqrt(dx * dx + dy * dy);
}

function nearestDistance(lat: number, lng: number): number {
  const cx = Math.floor(lat / HASH_STEP);
  const cy = Math.floor(lng / HASH_STEP);
  let best = Infinity;
  // Sweep the cell plus 8 neighbours; widens to a 3 × 3 grid if the
  // immediate buckets are empty (rare in the corridor).
  for (let radius = 1; radius <= 3 && !isFinite(best); radius++) {
    for (let dx = -radius; dx <= radius; dx++) {
      for (let dy = -radius; dy <= radius; dy++) {
        const list = buckets.get(`${cx + dx},${cy + dy}`);
        if (!list) continue;
        for (const p of list) {
          const d = distMeters(lat, lng, p.lat, p.lng);
          if (d < best) best = d;
        }
      }
    }
  }
  if (!isFinite(best)) {
    // Hash miss past 3.3 km: just give the cell a "very far" sentinel value
    // — we'll filter it out anyway.
    return Infinity;
  }
  return best;
}

console.log(`Computing coverage grid over ${BBOX.north - BBOX.south}° × ${BBOX.east - BBOX.west}° bbox…`);
console.log(`  → ${GTFS_STOPS.length} paraderos in spatial hash`);

const cells: Array<[number, number, number]> = [];
let scanned = 0;
for (let lat = BBOX.south; lat <= BBOX.north; lat += STEP) {
  for (let lng = BBOX.west; lng <= BBOX.east; lng += STEP) {
    scanned += 1;
    const d = nearestDistance(lat, lng);
    if (d > MAX_INTERESTING_M) continue;
    // Round lat/lng to 4 decimals (~11 m precision — invisible at city
    // zoom, halves the JSON size). Distance rounded to integer meters.
    cells.push([
      Math.round(lat * 1e4) / 1e4,
      Math.round(lng * 1e4) / 1e4,
      Math.round(d),
    ]);
  }
}

console.log(`  → scanned ${scanned.toLocaleString('en-US')} cells, kept ${cells.length.toLocaleString('en-US')}`);

const banner = `// AUTO-GENERATED by scripts/extract-coverage-grid.ts on ${new Date().toISOString()}.
// Paradero coverage grid over the Concepción metro bbox. Each entry is
// [lat, lng, distanceMetersToNearestParadero]. Step: ${STEP}° (~330 m).
// Cells beyond ${MAX_INTERESTING_M} m of any paradero were filtered out.
// Re-generate: \`npm run sync:coverage\`.

import type { CoverageCell } from '@/types/transport';
`;

// Inline output for size — JSON.stringify with no indentation would be
// equivalent but JavaScript array literals minify ~5 % better.
const body =
  '[\n' +
  cells.map(([la, ln, d]) => `  [${la},${ln},${d}],`).join('\n') +
  '\n]';

const output = `${banner}
export const COVERAGE_CELLS: CoverageCell[] = ${body};

export const COVERAGE_META = {
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  cells: ${cells.length},
  stepDeg: ${STEP},
  stepMeters: ${Math.round(STEP * M_PER_DEG_LAT)},
  bbox: ${JSON.stringify(BBOX)},
} as const;
`;

writeFileSync(OUT, output);
console.log(`Wrote ${OUT} (${(output.length / 1024).toFixed(1)} KB raw)`);
