// Pulls bus stops (highway=bus_stop + public_transport=platform) around the
// Concepción metro area from OSM Overpass and writes a typed module.
//
// Run: npm run sync:paraderos

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/paraderos.generated.ts');

// Bigger radius than terminals — we want stops in the urban core, not the
// entire region. ~12 km from Plaza Independencia covers Concepción + Talcahuano
// + San Pedro + Chiguayante.
const CENTER_LAT = -36.827;
const CENTER_LNG = -73.0498;
const RADIUS_M = 12_000;

interface OverpassNode {
  type: 'node';
  id: number;
  lat: number;
  lon: number;
  tags?: Record<string, string>;
}

async function queryOverpass() {
  return overpass<OverpassNode>(`[out:json][timeout:60];
(
  node["highway"="bus_stop"](around:${RADIUS_M},${CENTER_LAT},${CENTER_LNG});
);
out body;`);
}

interface Resolved {
  id: string;
  osmId: number;
  name?: string;
  lat: number;
  lng: number;
  operator?: string;
  shelter?: boolean;
  ref?: string;
}

function buildResolved(elements: OverpassNode[]): Resolved[] {
  return elements
    .filter((el) => el.type === 'node')
    .map((el): Resolved => {
      const tags = el.tags ?? {};
      const out: Resolved = {
        id: `osm-bs-${el.id}`,
        osmId: el.id,
        lat: el.lat,
        lng: el.lon,
      };
      if (tags.name) out.name = tags.name;
      if (tags.operator) out.operator = tags.operator;
      if (tags.shelter === 'yes') out.shelter = true;
      if (tags.ref) out.ref = tags.ref;
      return out;
    });
}

function render(stops: Resolved[]): string {
  const banner = `// AUTO-GENERATED by scripts/fetch-paraderos.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — node highway=bus_stop within ${(RADIUS_M / 1000) | 0} km of Plaza Independencia.
// Re-generate: \`npm run sync:paraderos\`. ${stops.length} stops.

import type { Paradero } from '@/types/transport';
`;
  const literal =
    '[\n' +
    stops
      .map((s) => {
        const parts = [`id:'${s.id}'`, `osmId:${s.osmId}`];
        if (s.name) parts.push(`name:${JSON.stringify(s.name)}`);
        parts.push(`lat:${s.lat}`, `lng:${s.lng}`);
        if (s.operator) parts.push(`operator:${JSON.stringify(s.operator)}`);
        if (s.shelter) parts.push(`shelter:true`);
        if (s.ref) parts.push(`ref:${JSON.stringify(s.ref)}`);
        return `  {${parts.join(',')}},`;
      })
      .join('\n') +
    '\n]';
  return `${banner}
export const PARADEROS: Paradero[] = ${literal};
`;
}

async function main() {
  console.log('Fetching bus stops from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} raw bus_stop nodes`);
  const stops = buildResolved(data.elements);
  console.log(`  → ${stops.length} paraderos written`);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(stops));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
