// Pulls major destinations (hospitals, universities, malls) around the
// Concepción metro from OSM and writes a typed module.
//
// Run: npm run sync:pois

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/pois.generated.ts');
const BBOX = '-37.10,-73.25,-36.65,-72.80';

type PoiCategory = 'hospital' | 'university' | 'college' | 'mall';

interface OverpassEl {
  type: 'node' | 'way' | 'relation';
  id: number;
  lat?: number;
  lon?: number;
  center?: { lat: number; lon: number };
  tags?: Record<string, string>;
}

async function queryOverpass() {
  return overpass<OverpassEl>(`[out:json][timeout:30];
(
  node["amenity"~"^(hospital|university|college)$"]["name"](${BBOX});
  way["amenity"~"^(hospital|university|college)$"]["name"](${BBOX});
  node["shop"="mall"]["name"](${BBOX});
  way["shop"="mall"]["name"](${BBOX});
);
out center tags;`);
}

interface Resolved {
  id: string;
  osmId: number;
  osmType: 'node' | 'way';
  name: string;
  category: PoiCategory;
  lat: number;
  lng: number;
}

function categorize(tags: Record<string, string>): PoiCategory | null {
  if (tags.shop === 'mall') return 'mall';
  const a = tags.amenity;
  if (a === 'hospital' || a === 'university' || a === 'college') return a;
  return null;
}

function buildResolved(elements: OverpassEl[]): Resolved[] {
  const out: Resolved[] = [];
  const dedupe = new Map<string, true>();
  for (const el of elements) {
    if (el.type === 'relation') continue;
    const tags = el.tags ?? {};
    const cat = categorize(tags);
    const name = tags.name;
    const lat = el.lat ?? el.center?.lat;
    const lon = el.lon ?? el.center?.lon;
    if (!cat || !name || lat == null || lon == null) continue;
    const key = `${name}|${lat.toFixed(4)},${lon.toFixed(4)}`;
    if (dedupe.has(key)) continue;
    dedupe.set(key, true);
    out.push({
      id: `osm-${el.type}-${el.id}`,
      osmId: el.id,
      osmType: el.type,
      name,
      category: cat,
      lat,
      lng: lon,
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name, 'es'));
  return out;
}

function render(pois: Resolved[]): string {
  const counts = pois.reduce<Record<string, number>>((acc, p) => {
    acc[p.category] = (acc[p.category] ?? 0) + 1;
    return acc;
  }, {});
  const summary = Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .map(([c, n]) => `${n} ${c}`)
    .join(' · ');

  const banner = `// AUTO-GENERATED by scripts/fetch-pois.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — destinos relevantes en el bbox
// metropolitano: amenity=hospital|university|college + shop=mall.
// ${pois.length} POIs total — ${summary}.
// Re-generate: \`npm run sync:pois\`.

import type { Poi } from '@/types/transport';
`;
  const literal =
    '[\n' +
    pois
      .map((p) => {
        return `  { id:'${p.id}',osmId:${p.osmId},osmType:${JSON.stringify(p.osmType)},name:${JSON.stringify(p.name)},category:${JSON.stringify(p.category)},lat:${p.lat},lng:${p.lng} },`;
      })
      .join('\n') +
    '\n]';
  return `${banner}
export const POIS: Poi[] = ${literal};
`;
}

async function main() {
  console.log('Fetching POIs from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} raw elements`);
  const pois = buildResolved(data.elements);
  console.log(`  → ${pois.length} POIs after de-dup`);
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(pois));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
