// Pulls the cycling infrastructure of Gran Concepción from OSM —
// dedicated cycleways (highway=cycleway), bicycle-designated paths,
// and on-road bike lanes (cycleway=lane / cycleway:*=lane). Writes a
// typed module for the visor.
//
// Run: npm run sync:cycleways

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/cycleways.generated.ts');
const BBOX = '-37.10,-73.25,-36.65,-72.80';

type CyclewayKind = 'segregated' | 'shared' | 'lane';

interface OverpassWay {
  type: 'way';
  id: number;
  geometry?: Array<{ lat: number; lon: number }>;
  tags?: Record<string, string>;
}

async function queryOverpass() {
  // Three slices:
  //   - dedicated cycleways (highway=cycleway): segregated infrastructure
  //   - paths with bicycle=designated: shared with pedestrians
  //   - roads with a cycleway lane tag: in-traffic bike lanes
  return overpass<OverpassWay>(`[out:json][timeout:60];
(
  way["highway"="cycleway"](${BBOX});
  way["highway"="path"]["bicycle"="designated"](${BBOX});
  way["highway"~"^(primary|secondary|tertiary|residential|unclassified)$"]["cycleway"~"lane|track"](${BBOX});
  way["highway"~"^(primary|secondary|tertiary|residential|unclassified)$"]["cycleway:both"~"lane|track"](${BBOX});
  way["highway"~"^(primary|secondary|tertiary|residential|unclassified)$"]["cycleway:right"~"lane|track"](${BBOX});
  way["highway"~"^(primary|secondary|tertiary|residential|unclassified)$"]["cycleway:left"~"lane|track"](${BBOX});
);
out geom tags;`);
}

interface Resolved {
  id: string;
  kind: CyclewayKind;
  name: string | null;
  surface: string | null;
  /** Polyline as [lat, lng] vertices. */
  path: Array<[number, number]>;
}

function classifyKind(tags: Record<string, string>): CyclewayKind {
  if (tags.highway === 'cycleway') return 'segregated';
  if (tags.highway === 'path' && tags.bicycle === 'designated') return 'shared';
  return 'lane';
}

function buildResolved(elements: OverpassWay[]): Resolved[] {
  const out: Resolved[] = [];
  const seen = new Set<number>();
  for (const el of elements) {
    if (el.type !== 'way' || seen.has(el.id)) continue;
    seen.add(el.id);
    const tags = el.tags ?? {};
    const geom = el.geometry;
    if (!geom || geom.length < 2) continue;
    out.push({
      id: `osm-way-${el.id}`,
      kind: classifyKind(tags),
      name: tags.name ?? null,
      surface: tags.surface ?? null,
      path: geom.map((g) => [g.lat, g.lon] as [number, number]),
    });
  }
  return out;
}

function render(items: Resolved[]): string {
  const km = items.reduce((acc, it) => acc + pathKm(it.path), 0);
  const byKind = items.reduce<Record<string, number>>((acc, it) => {
    acc[it.kind] = (acc[it.kind] ?? 0) + 1;
    return acc;
  }, {});

  const banner = `// AUTO-GENERATED by scripts/fetch-cycleways.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — infraestructura ciclista en
// el bbox metropolitano Gran Concepción.
// ${items.length} tramos · ${km.toFixed(1)} km totales · ${JSON.stringify(byKind)}.
// Re-generate: \`npm run sync:cycleways\`.

export type CyclewayKind = 'segregated' | 'shared' | 'lane';

export interface Cycleway {
  id: string;
  kind: CyclewayKind;
  name: string | null;
  surface: string | null;
  path: Array<[number, number]>;
}
`;

  // Compact literal form to keep bundle size reasonable. We don't
  // bother with explicit type annotation per element — the array
  // type assertion is enough.
  const lines = items.map((it) => {
    const path = it.path
      .map(([lat, lng]) => `[${lat.toFixed(5)},${lng.toFixed(5)}]`)
      .join(',');
    return `  {id:${JSON.stringify(it.id)},kind:${JSON.stringify(it.kind)},name:${JSON.stringify(it.name)},surface:${JSON.stringify(it.surface)},path:[${path}]},`;
  });

  return `${banner}
export const CYCLEWAYS: Cycleway[] = [
${lines.join('\n')}
];
`;
}

function pathKm(path: Array<[number, number]>): number {
  let km = 0;
  for (let i = 1; i < path.length; i++) {
    const R = 6371;
    const [aLat, aLng] = path[i - 1];
    const [bLat, bLng] = path[i];
    const dLat = ((bLat - aLat) * Math.PI) / 180;
    const dLng = ((bLng - aLng) * Math.PI) / 180;
    const lat1 = (aLat * Math.PI) / 180;
    const lat2 = (bLat * Math.PI) / 180;
    const x =
      Math.sin(dLat / 2) ** 2 +
      Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
    km += 2 * R * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x));
  }
  return km;
}

async function main() {
  console.log('Fetching cycling infrastructure from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} raw ways`);
  const items = buildResolved(data.elements);
  const km = items.reduce((acc, it) => acc + pathKm(it.path), 0);
  console.log(`  → ${items.length} tramos · ${km.toFixed(1)} km`);
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(items));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
