// Pulls public green spaces (parks, plazas, urban forests) for the Gran
// Concepción metro from OSM as polygons + optional name. Lays the
// groundwork for OMS-style "m² of green space per habitant" analytics.
//
// Run: npm run sync:greenspace

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/greenspace.generated.ts');
const BBOX = '-37.10,-73.25,-36.65,-72.80';

type GreenKind = 'park' | 'garden' | 'plaza' | 'forest' | 'nature_reserve';

interface OverpassEl {
  type: 'way' | 'relation';
  id: number;
  geometry?: Array<{ lat: number; lon: number }>;
  members?: Array<{
    type: 'way' | 'node' | 'relation';
    role: string;
    geometry?: Array<{ lat: number; lon: number }>;
  }>;
  tags?: Record<string, string>;
}

async function queryOverpass() {
  return overpass<OverpassEl>(`[out:json][timeout:90];
(
  way["leisure"="park"](${BBOX});
  way["leisure"="garden"](${BBOX});
  way["leisure"="nature_reserve"](${BBOX});
  way["landuse"="forest"](${BBOX});
  way["highway"="pedestrian"]["area"="yes"](${BBOX});
  relation["leisure"="park"](${BBOX});
  relation["leisure"="nature_reserve"](${BBOX});
);
out geom tags;`);
}

interface Resolved {
  id: string;
  kind: GreenKind;
  name: string | null;
  /** Ring of [lat, lng] vertices. Closed (first == last not enforced). */
  ring: Array<[number, number]>;
  /** Rough area in m² (planar, mercator-skewed but good enough at this lat). */
  areaM2: number;
}

function classifyKind(tags: Record<string, string>): GreenKind {
  if (tags.leisure === 'park') {
    // Many plazas in Chile are tagged leisure=park; distinguish only when
    // the name explicitly says "plaza".
    if (/plaza\s/i.test(tags.name ?? '')) return 'plaza';
    return 'park';
  }
  if (tags.leisure === 'garden') return 'garden';
  if (tags.leisure === 'nature_reserve') return 'nature_reserve';
  if (tags.landuse === 'forest') return 'forest';
  if (tags.highway === 'pedestrian' && tags.area === 'yes') return 'plaza';
  return 'park';
}

// Shoelace area in m², converting lat/lng to local mercator-meters via the
// equirectangular approximation at the local latitude (good for small areas).
function ringAreaM2(ring: Array<[number, number]>): number {
  if (ring.length < 3) return 0;
  const lat0 = ring.reduce((a, p) => a + p[0], 0) / ring.length;
  const cosLat = Math.cos((lat0 * Math.PI) / 180);
  const mPerDegLat = 111_132;
  const mPerDegLng = mPerDegLat * cosLat;
  let area = 0;
  for (let i = 0; i < ring.length; i++) {
    const [lat1, lng1] = ring[i];
    const [lat2, lng2] = ring[(i + 1) % ring.length];
    const x1 = lng1 * mPerDegLng;
    const y1 = lat1 * mPerDegLat;
    const x2 = lng2 * mPerDegLng;
    const y2 = lat2 * mPerDegLat;
    area += x1 * y2 - x2 * y1;
  }
  return Math.abs(area / 2);
}

function buildResolved(elements: OverpassEl[]): Resolved[] {
  const out: Resolved[] = [];
  const seen = new Set<string>();
  for (const el of elements) {
    const tags = el.tags ?? {};
    const kind = classifyKind(tags);
    const key = `${el.type}-${el.id}`;
    if (seen.has(key)) continue;

    let ring: Array<[number, number]> | null = null;
    if (el.type === 'way' && el.geometry) {
      ring = el.geometry.map((g) => [g.lat, g.lon] as [number, number]);
    } else if (el.type === 'relation' && el.members) {
      // Use the outer ring of the first multipolygon. Concat all outer
      // members is technically more correct for donuts but rare in the
      // dataset and we'd need to dedupe — skip for now.
      const outer = el.members.find((m) => m.role === 'outer' && m.geometry);
      if (outer && outer.geometry) {
        ring = outer.geometry.map((g) => [g.lat, g.lon] as [number, number]);
      }
    }
    if (!ring || ring.length < 4) continue;

    const areaM2 = ringAreaM2(ring);
    // Filter tiny noise: ignore parks under 200 m² (smaller than a basketball
    // court — usually mis-tagged residential corners).
    if (areaM2 < 200) continue;

    seen.add(key);
    out.push({
      id: `osm-${el.type}-${el.id}`,
      kind,
      name: tags.name ?? null,
      ring,
      areaM2,
    });
  }
  // Sort largest first so big nature reserves render under small plazas.
  out.sort((a, b) => b.areaM2 - a.areaM2);
  return out;
}

function render(items: Resolved[]): string {
  const totalKm2 = items.reduce((acc, it) => acc + it.areaM2 / 1_000_000, 0);
  const byKind = items.reduce<Record<string, number>>((acc, it) => {
    acc[it.kind] = (acc[it.kind] ?? 0) + 1;
    return acc;
  }, {});

  const banner = `// AUTO-GENERATED by scripts/fetch-greenspace.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — parques, jardines, plazas y
// reservas naturales del bbox metropolitano Gran Concepción.
// ${items.length} polígonos · ${totalKm2.toFixed(1)} km² · ${JSON.stringify(byKind)}.
// Re-generate: \`npm run sync:greenspace\`.

export type GreenKind = 'park' | 'garden' | 'plaza' | 'forest' | 'nature_reserve';

export interface GreenSpace {
  id: string;
  kind: GreenKind;
  name: string | null;
  /** Closed ring of [lat, lng] vertices. */
  ring: Array<[number, number]>;
  /** Approximate area in m². */
  areaM2: number;
}
`;

  const lines = items.map((it) => {
    const ring = it.ring
      .map(([lat, lng]) => `[${lat.toFixed(5)},${lng.toFixed(5)}]`)
      .join(',');
    return `  {id:${JSON.stringify(it.id)},kind:${JSON.stringify(it.kind)},name:${JSON.stringify(it.name)},areaM2:${Math.round(it.areaM2)},ring:[${ring}]},`;
  });

  // `as unknown as GreenSpace[]` — with 2k+ polygons + a `kind` union, the
  // structural inference exceeds TS's complexity limit. Going through
  // `unknown` skips the per-element check while still typing consumers.
  return `${banner}
export const GREEN_SPACES = ([
${lines.join('\n')}
] as unknown) as GreenSpace[];
`;
}

async function main() {
  console.log('Fetching green spaces from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} raw elements`);
  const items = buildResolved(data.elements);
  const totalKm2 = items.reduce((acc, it) => acc + it.areaM2 / 1_000_000, 0);
  console.log(`  → ${items.length} polígonos · ${totalKm2.toFixed(1)} km²`);
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(items));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
