// Pulls intermodal stations + bus terminals around greater Concepción from OSM
// (Overpass), keeps only named amenities, and writes a typed module.
//
// Run: npm run sync:terminals

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/terminals.generated.ts');

const BBOX = '-37.10,-73.25,-36.65,-72.80';

interface OverpassEl {
  type: 'node' | 'way' | 'relation';
  id: number;
  lat?: number;
  lon?: number;
  center?: { lat: number; lon: number };
  tags?: Record<string, string>;
}

async function queryOverpass() {
  return overpass<OverpassEl>(`[out:json][timeout:30];
(
  node["amenity"="bus_station"](${BBOX});
  way["amenity"="bus_station"](${BBOX});
  node["public_transport"="station"]["bus"="yes"](${BBOX});
);
out center tags;`);
}

interface Resolved {
  id: string;
  osmId: number;
  name: string;
  lat: number;
  lng: number;
  network?: string;
  operator?: string;
}

function resolve_(elements: OverpassEl[]): Resolved[] {
  const out: Resolved[] = [];
  const seenIds = new Set<number>();
  const seenNamesAtCoord = new Map<string, true>();

  for (const el of elements) {
    if (seenIds.has(el.id)) continue;
    const lat = el.lat ?? el.center?.lat;
    const lon = el.lon ?? el.center?.lon;
    const name = el.tags?.name;
    if (lat == null || lon == null || !name || name.length < 3) continue;

    const dedupeKey = `${name}|${lat.toFixed(4)},${lon.toFixed(4)}`;
    if (seenNamesAtCoord.has(dedupeKey)) continue;
    seenNamesAtCoord.set(dedupeKey, true);

    seenIds.add(el.id);
    out.push({
      id: `osm-${el.type}-${el.id}`,
      osmId: el.id,
      name,
      lat,
      lng: lon,
      network: el.tags?.network,
      operator: el.tags?.operator,
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name, 'es'));
  return out;
}

function render(terminals: Resolved[]): string {
  const banner = `// AUTO-GENERATED by scripts/fetch-terminals.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — amenity=bus_station + public_transport=station
// within the Biobío bbox. Re-generate: \`npm run sync:terminals\`.

import type { Terminal } from '@/types/transport';
`;
  const literal =
    '[\n' +
    terminals
      .map((t) => {
        const extra: string[] = [];
        if (t.network) extra.push(`network: ${JSON.stringify(t.network)}`);
        if (t.operator) extra.push(`operator: ${JSON.stringify(t.operator)}`);
        const extraStr = extra.length ? `, ${extra.join(', ')}` : '';
        return `  { id: '${t.id}', osmId: ${t.osmId}, name: ${JSON.stringify(t.name)}, lat: ${t.lat}, lng: ${t.lng}${extraStr} },`;
      })
      .join('\n') +
    '\n]';
  return `${banner}
export const TERMINALS: Terminal[] = ${literal};
`;
}

async function main() {
  console.log('Fetching transit terminals from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} raw elements`);
  const terminals = resolve_(data.elements);
  console.log(`  → ${terminals.length} named terminals after de-dup`);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(terminals));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
