// Enriches Biotrén stations with Wikidata facts: service-entry date (P1619),
// image (P18), Spanish Wikipedia article URL. Only stations with a wikidata
// Q-id in biotren.generated.ts are queried.
//
// Run: npm run sync:wikidata

import { spawn } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BIOTREN_L1_STOPS, BIOTREN_L2_STOPS } from '../src/data/biotren.generated.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/wikidata.generated.ts');

const ENDPOINT = 'https://query.wikidata.org/sparql';
const UA = 'conce-patagua-dev/0.1 (https://github.com/marcorojasb/conce.patagua.dev) — contact via repo issues';

function curlGet(url: string): Promise<string> {
  return new Promise((res, rej) => {
    const c = spawn('curl', [
      '-sS',
      '-m', '30',
      '-H', `User-Agent: ${UA}`,
      '-H', 'Accept: application/sparql-results+json',
      url,
    ]);
    let out = '';
    let err = '';
    c.stdout.on('data', (b: Buffer) => (out += b.toString('utf8')));
    c.stderr.on('data', (b: Buffer) => (err += b.toString('utf8')));
    c.on('close', (code) => (code === 0 ? res(out) : rej(new Error(`curl ${code}: ${err}`))));
    c.on('error', rej);
  });
}

interface SparqlBinding {
  item?: { value: string };
  serviceDate?: { value: string };
  image?: { value: string };
  article?: { value: string };
}

interface SparqlResults {
  results: { bindings: SparqlBinding[] };
}

interface Enrichment {
  qid: string;
  openedYear?: number;
  imageUrl?: string;
  wikipediaEs?: string;
}

async function runQuery(qids: string[]): Promise<Enrichment[]> {
  const values = qids.map((q) => `wd:${q}`).join(' ');
  const sparql = `SELECT ?item ?serviceDate ?image ?article WHERE {
  VALUES ?item { ${values} }
  OPTIONAL { ?item wdt:P1619 ?serviceDate. }
  OPTIONAL { ?item wdt:P18 ?image. }
  OPTIONAL {
    ?article schema:about ?item ;
             schema:isPartOf <https://es.wikipedia.org/> .
  }
}`;
  const url = `${ENDPOINT}?query=${encodeURIComponent(sparql)}&format=json`;
  const body = await curlGet(url);
  const data = JSON.parse(body) as SparqlResults;

  const byQ = new Map<string, Enrichment>();
  for (const qid of qids) byQ.set(qid, { qid });
  for (const b of data.results.bindings) {
    const itemUri = b.item?.value;
    if (!itemUri) continue;
    const qid = itemUri.split('/').pop()!;
    const e = byQ.get(qid);
    if (!e) continue;
    if (b.serviceDate?.value && !e.openedYear) {
      const y = new Date(b.serviceDate.value).getUTCFullYear();
      if (Number.isFinite(y)) e.openedYear = y;
    }
    if (b.image?.value && !e.imageUrl) {
      // Convert "http://commons.wikimedia.org/wiki/Special:FilePath/Foo.jpg"
      // into a thumbnail URL via Wikimedia's Special:FilePath endpoint.
      e.imageUrl = `${b.image.value}?width=480`;
    }
    if (b.article?.value && !e.wikipediaEs) {
      e.wikipediaEs = b.article.value;
    }
  }
  return Array.from(byQ.values());
}

function render(entries: Enrichment[]): string {
  const banner = `// AUTO-GENERATED by scripts/fetch-wikidata.ts on ${new Date().toISOString()}.
// Source: Wikidata SPARQL endpoint. Enrichment keyed by Wikidata Q-id for the
// Biotrén stations that have one tagged in OSM (${entries.length} stations).
// Re-generate: \`npm run sync:wikidata\`.

import type { WikidataEnrichment } from '@/types/transport';
`;
  const map =
    '{\n' +
    entries
      .filter((e) => e.openedYear || e.imageUrl || e.wikipediaEs)
      .map((e) => {
        const parts: string[] = [];
        if (e.openedYear) parts.push(`openedYear:${e.openedYear}`);
        if (e.imageUrl) parts.push(`imageUrl:${JSON.stringify(e.imageUrl)}`);
        if (e.wikipediaEs) parts.push(`wikipediaEs:${JSON.stringify(e.wikipediaEs)}`);
        return `  '${e.qid}': { ${parts.join(', ')} },`;
      })
      .join('\n') +
    '\n}';
  return `${banner}
export const BIOTREN_WIKIDATA: Record<string, WikidataEnrichment> = ${map};
`;
}

async function main() {
  const stops = [...BIOTREN_L1_STOPS, ...BIOTREN_L2_STOPS];
  const qids = Array.from(new Set(stops.map((s) => s.wikidata).filter((q): q is string => !!q)));
  console.log(`Fetching Wikidata enrichment for ${qids.length} Biotrén stations…`);
  const enrichments = await runQuery(qids);
  const useful = enrichments.filter((e) => e.openedYear || e.imageUrl || e.wikipediaEs);
  console.log(`  → ${useful.length}/${qids.length} stations had any usable data`);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(enrichments));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
