// Educational establishments for the Gran Concepción metro from OSM.
// Captures kindergarten / school / college (university already lives in
// pois.generated.ts as a "destino", but a dedicated education layer is
// the right home for the wider K-12 set).
//
// Run: npm run sync:schools

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/schools.generated.ts');
const BBOX = '-37.10,-73.25,-36.65,-72.80';

type SchoolKind = 'kindergarten' | 'school' | 'college' | 'university';

interface OverpassEl {
  type: 'node' | 'way' | 'relation';
  id: number;
  lat?: number;
  lon?: number;
  center?: { lat: number; lon: number };
  tags?: Record<string, string>;
}

async function queryOverpass() {
  return overpass<OverpassEl>(`[out:json][timeout:60];
(
  node["amenity"~"^(kindergarten|school|college|university)$"]["name"](${BBOX});
  way["amenity"~"^(kindergarten|school|college|university)$"]["name"](${BBOX});
  relation["amenity"~"^(kindergarten|school|college|university)$"]["name"](${BBOX});
);
out center tags;`);
}

interface Resolved {
  id: string;
  kind: SchoolKind;
  name: string;
  /** Operator if tagged (often "público" / "privado" / nombre del colegio). */
  operator: string | null;
  /** Religion if tagged — useful in CL where many private schools are religious. */
  religion: string | null;
  lat: number;
  lng: number;
}

function classifyKind(tags: Record<string, string>): SchoolKind | null {
  const a = tags.amenity;
  if (a === 'kindergarten' || a === 'school' || a === 'college' || a === 'university')
    return a;
  return null;
}

function buildResolved(elements: OverpassEl[]): Resolved[] {
  const out: Resolved[] = [];
  const dedupe = new Map<string, true>();
  for (const el of elements) {
    const tags = el.tags ?? {};
    const kind = classifyKind(tags);
    const name = tags.name;
    const lat = el.lat ?? el.center?.lat;
    const lon = el.lon ?? el.center?.lon;
    if (!kind || !name || lat == null || lon == null) continue;
    const key = `${name}|${lat.toFixed(4)},${lon.toFixed(4)}`;
    if (dedupe.has(key)) continue;
    dedupe.set(key, true);
    out.push({
      id: `osm-${el.type}-${el.id}`,
      kind,
      name,
      operator: tags.operator ?? null,
      religion: tags.religion ?? null,
      lat,
      lng: lon,
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name, 'es'));
  return out;
}

function render(items: Resolved[]): string {
  const byKind = items.reduce<Record<string, number>>((acc, it) => {
    acc[it.kind] = (acc[it.kind] ?? 0) + 1;
    return acc;
  }, {});

  const banner = `// AUTO-GENERATED by scripts/fetch-schools.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — establecimientos educacionales
// en el bbox metropolitano Gran Concepción.
// ${items.length} establecimientos · ${JSON.stringify(byKind)}.
// Re-generate: \`npm run sync:schools\`.

export type SchoolKind = 'kindergarten' | 'school' | 'college' | 'university';

export interface School {
  id: string;
  kind: SchoolKind;
  name: string;
  operator: string | null;
  religion: string | null;
  lat: number;
  lng: number;
}
`;

  const lines = items.map((s) => {
    return `  {id:${JSON.stringify(s.id)},kind:${JSON.stringify(s.kind)},name:${JSON.stringify(s.name)},operator:${JSON.stringify(s.operator)},religion:${JSON.stringify(s.religion)},lat:${s.lat},lng:${s.lng}},`;
  });

  return `${banner}
export const SCHOOLS: School[] = [
${lines.join('\n')}
];
`;
}

async function main() {
  console.log('Fetching schools from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} raw elements`);
  const items = buildResolved(data.elements);
  console.log(`  → ${items.length} establecimientos`);
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(items));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
