// Pulls all OSM bus route relations in the greater Concepción metro area
// and emits a typed module with each route's polyline geometry.
//
// Run: npm run sync:bus-routes
//
// Output is a self-contained list of routes — no station references back
// into the OSM graph. Stops are not included here because the separate
// `paraderos.generated` layer already covers them.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { overpass } from './lib/overpass.ts';
import { simplify } from './lib/simplify.ts';
import { cumulativeDistances, nearestVertex } from './lib/geo.ts';
import { PARADEROS } from '../src/data/paraderos.generated.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/bus-routes.generated.ts');

const BBOX = '-37.10,-73.25,-36.65,-72.80';

interface OverpassRelation {
  type: 'relation';
  id: number;
  members: Array<{
    type: 'node' | 'way' | 'relation';
    ref: number;
    role: string;
    geometry?: Array<{ lat: number; lon: number }>;
  }>;
  tags?: Record<string, string>;
}

async function queryOverpass() {
  return overpass<OverpassRelation>(`[out:json][timeout:90];
relation["type"="route"]["route"="bus"](${BBOX});
out geom;`);
}

interface Resolved {
  id: string;
  osmId: number;
  ref: string;
  name: string;
  operator?: string;
  network?: string;
  colour?: string;
  /** Flat polyline of [lat, lng] pairs, stitched from way members in order. */
  path: Array<[number, number]>;
  /** Paradero ids matched to this route by ≤30 m proximity, ordered along the path. */
  stopIds: string[];
}

const MATCH_DISTANCE_M = 30;

function dedupConsecutive(path: Array<[number, number]>): Array<[number, number]> {
  const out: Array<[number, number]> = [];
  let prev: [number, number] | null = null;
  for (const p of path) {
    if (prev && Math.abs(prev[0] - p[0]) < 1e-7 && Math.abs(prev[1] - p[1]) < 1e-7) {
      continue;
    }
    out.push(p);
    prev = p;
  }
  return out;
}

/** Rounds coords to 5 decimals (~1 m precision) to cut JSON size by ~30%. */
function round5(n: number): number {
  return Math.round(n * 1e5) / 1e5;
}

/**
 * Returns paradero ids whose nearest vertex on `path` is within
 * MATCH_DISTANCE_M, sorted by their progress along the polyline. Consecutive
 * duplicates are collapsed (a paradero can be the closest to several adjacent
 * vertices after simplification).
 */
function matchParaderos(path: Array<[number, number]>): string[] {
  const cum = cumulativeDistances(path);
  const matched: Array<{ id: string; progress: number }> = [];
  for (const p of PARADEROS) {
    const { idx, d } = nearestVertex(path, [p.lat, p.lng]);
    if (d <= MATCH_DISTANCE_M) {
      matched.push({ id: p.id, progress: cum[idx] });
    }
  }
  matched.sort((a, b) => a.progress - b.progress);
  const out: string[] = [];
  for (const m of matched) {
    if (out[out.length - 1] !== m.id) out.push(m.id);
  }
  return out;
}

function buildRoute(rel: OverpassRelation): Resolved | null {
  const tags = rel.tags ?? {};
  const ref = tags.ref;
  const name = tags.name;
  if (!ref || !name) return null;

  // Collect all way geometries in the order they appear in the relation.
  // Skip nodes (stop members) — paraderos.generated covers those.
  const path: Array<[number, number]> = [];
  for (const m of rel.members) {
    if (m.type !== 'way' || !m.geometry) continue;
    for (const pt of m.geometry) {
      path.push([round5(pt.lat), round5(pt.lon)]);
    }
  }

  // 1.5e-4 ≈ 16 m at Concepción latitude — invisible at city zoom, cuts
  // the bundle by ~85 %.
  const cleaned = simplify(dedupConsecutive(path), 1.5e-4);
  if (cleaned.length < 2) return null;
  const stopIds = matchParaderos(cleaned);

  const out: Resolved = {
    id: `osm-bus-${rel.id}`,
    osmId: rel.id,
    ref,
    name,
    path: cleaned,
    stopIds,
  };
  if (tags.operator) out.operator = tags.operator;
  if (tags.network) out.network = tags.network;
  if (tags.colour) out.colour = tags.colour;
  return out;
}

function render(routes: Resolved[]): string {
  const banner = `// AUTO-GENERATED by scripts/fetch-bus-routes.ts on ${new Date().toISOString()}.
// Source: OpenStreetMap (Overpass API) — type=route route=bus relations
// within the Biobío metro bbox. ${routes.length} routes total.
// Re-generate: \`npm run sync:bus-routes\`.

import type { BusRoute } from '@/types/transport';
`;
  const literal =
    '[\n' +
    routes
      .map((r) => {
        const parts = [
          `id:'${r.id}'`,
          `osmId:${r.osmId}`,
          `ref:${JSON.stringify(r.ref)}`,
          `name:${JSON.stringify(r.name)}`,
        ];
        if (r.operator) parts.push(`operator:${JSON.stringify(r.operator)}`);
        if (r.network) parts.push(`network:${JSON.stringify(r.network)}`);
        if (r.colour) parts.push(`colour:${JSON.stringify(r.colour)}`);
        const pathStr = '[' + r.path.map(([la, ln]) => `[${la},${ln}]`).join(',') + ']';
        parts.push(`path:${pathStr}`);
        const stopsStr = '[' + r.stopIds.map((id) => JSON.stringify(id)).join(',') + ']';
        parts.push(`stopIds:${stopsStr}`);
        return `  {${parts.join(',')}},`;
      })
      .join('\n') +
    '\n]';
  return `${banner}
export const BUS_ROUTES: BusRoute[] = ${literal};
`;
}

async function main() {
  console.log('Fetching bus route relations from Overpass…');
  const data = await queryOverpass();
  console.log(`  → ${data.elements.length} relations`);
  const routes = data.elements
    .map(buildRoute)
    .filter((r): r is Resolved => r !== null);
  console.log(`  → ${routes.length} routes with usable geometry`);

  const totalPts = routes.reduce((acc, r) => acc + r.path.length, 0);
  const totalStops = routes.reduce((acc, r) => acc + r.stopIds.length, 0);
  console.log(`  → ${totalPts} polyline points · ${totalStops} stop matches`);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, render(routes));
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
