import { useCallback, useEffect, useMemo, useState } from 'react';
import { MapPin } from 'lucide-react';
import { ConceMap } from '@/components/conce-map';
import { Header } from '@/components/header';
import { RouteDetailSheet } from '@/components/route-detail-sheet';
import { Sidebar } from '@/components/sidebar';
import { StopDetailSheet } from '@/components/stop-detail-sheet';
import { TerminalDetailSheet } from '@/components/terminal-detail-sheet';
import { Card, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Kbd } from '@/components/ui/kbd';
import { ROUTES, ROUTE_TYPES, STOPS } from '@/data/routes';
import { TERMINALS } from '@/data/terminals.generated';
import { useTheme } from '@/hooks/use-theme';
import type { FlyToToken, Paradero, RouteTypeId, SheetKind } from '@/types/transport';

// Approximate paradero count, used as the sidebar badge before the chunk has
// loaded. Re-generated by `npm run sync:paraderos` — kept in sync manually.
const PARADEROS_APPROX_COUNT = 1776;

export default function App() {
  const [theme, toggleTheme] = useTheme();
  const [sidebarOpen, setSidebarOpen] = useState(true);

  const [visibleRouteIds, setVisibleRouteIds] = useState<string[]>(() =>
    ROUTES.map((r) => r.id),
  );
  const [typeFilters, setTypeFilters] = useState<Record<RouteTypeId, boolean>>(() =>
    Object.fromEntries(
      (Object.keys(ROUTE_TYPES) as RouteTypeId[]).map((k) => [k, true]),
    ) as Record<RouteTypeId, boolean>,
  );

  const [selectedRouteId, setSelectedRouteId] = useState<string | null>(null);
  const [selectedStopId, setSelectedStopId] = useState<string | null>(null);
  const [selectedTerminalId, setSelectedTerminalId] = useState<string | null>(null);
  const [sheetKind, setSheetKind] = useState<SheetKind>(null);

  const [showTerminals, setShowTerminals] = useState(true);
  const [showParaderos, setShowParaderos] = useState(false);

  // Paraderos are ~1.7k records → ~60 KB gz. Load the chunk only the first
  // time the layer is enabled.
  const [paraderos, setParaderos] = useState<Paradero[]>([]);
  useEffect(() => {
    if (!showParaderos || paraderos.length) return;
    let cancelled = false;
    void import('@/data/paraderos.generated').then((mod) => {
      if (!cancelled) setParaderos(mod.PARADEROS);
    });
    return () => {
      cancelled = true;
    };
  }, [showParaderos, paraderos.length]);

  const [flyToToken, setFlyToToken] = useState<FlyToToken | null>(null);

  const selectedRoute = useMemo(
    () => ROUTES.find((r) => r.id === selectedRouteId) ?? null,
    [selectedRouteId],
  );
  const selectedStop = useMemo(
    () => STOPS.find((s) => s.id === selectedStopId) ?? null,
    [selectedStopId],
  );
  const selectedTerminal = useMemo(
    () => TERMINALS.find((t) => t.id === selectedTerminalId) ?? null,
    [selectedTerminalId],
  );

  const visibleIdsAfterTypeFilter = useMemo(() => {
    return visibleRouteIds.filter((id) => {
      const r = ROUTES.find((x) => x.id === id);
      return r && typeFilters[r.type];
    });
  }, [visibleRouteIds, typeFilters]);

  const onToggleVisible = useCallback((id: string) => {
    setVisibleRouteIds((cur) =>
      cur.includes(id) ? cur.filter((x) => x !== id) : [...cur, id],
    );
  }, []);

  const onToggleType = useCallback((typeId: RouteTypeId) => {
    setTypeFilters((f) => ({ ...f, [typeId]: !f[typeId] }));
  }, []);

  const onSelectRoute = useCallback((id: string) => {
    const r = ROUTES.find((x) => x.id === id);
    if (!r) return;
    setVisibleRouteIds((cur) => (cur.includes(id) ? cur : [...cur, id]));
    setTypeFilters((f) => ({ ...f, [r.type]: true }));
    setSelectedRouteId(id);
    setSelectedStopId(null);
    setSelectedTerminalId(null);
    setSheetKind('route');
    setFlyToToken({ key: Date.now(), target: { kind: 'bounds', path: r.path } });
  }, []);

  const onSelectStop = useCallback((id: string) => {
    const s = STOPS.find((x) => x.id === id);
    if (!s) return;
    setSelectedStopId(id);
    setSelectedTerminalId(null);
    setSheetKind('stop');
    setFlyToToken({
      key: Date.now(),
      target: { kind: 'point', lat: s.lat, lng: s.lng, zoom: 16 },
    });
  }, []);

  const onSelectTerminal = useCallback((id: string) => {
    const t = TERMINALS.find((x) => x.id === id);
    if (!t) return;
    setSelectedTerminalId(id);
    setSelectedRouteId(null);
    setSelectedStopId(null);
    setSheetKind('terminal');
    setFlyToToken({
      key: Date.now(),
      target: { kind: 'point', lat: t.lat, lng: t.lng, zoom: 16 },
    });
  }, []);

  const onSelectParadero = useCallback(
    (id: string) => {
      const p = paraderos.find((x) => x.id === id);
      if (!p) return;
      setFlyToToken({
        key: Date.now(),
        target: { kind: 'point', lat: p.lat, lng: p.lng, zoom: 17 },
      });
    },
    [paraderos],
  );

  const closeSheet = useCallback(() => {
    setSheetKind(null);
    setSelectedRouteId(null);
    setSelectedStopId(null);
    setSelectedTerminalId(null);
  }, []);

  const onFocusRoute = useCallback(() => {
    if (!selectedRoute) return;
    setFlyToToken({
      key: Date.now(),
      target: { kind: 'bounds', path: selectedRoute.path },
    });
  }, [selectedRoute]);

  const onFocusTerminal = useCallback(() => {
    if (!selectedTerminal) return;
    setFlyToToken({
      key: Date.now(),
      target: { kind: 'point', lat: selectedTerminal.lat, lng: selectedTerminal.lng, zoom: 16 },
    });
  }, [selectedTerminal]);

  return (
    <div className="flex h-full w-full flex-col bg-background text-foreground">
      <Header
        theme={theme}
        onToggleTheme={toggleTheme}
        onToggleSidebar={() => setSidebarOpen((o) => !o)}
        onSelectRoute={onSelectRoute}
        onSelectStop={onSelectStop}
      />

      <div className="relative flex min-h-0 flex-1">
        <Sidebar
          open={sidebarOpen}
          routes={ROUTES}
          visibleRouteIds={visibleRouteIds}
          onToggleVisible={onToggleVisible}
          selectedRouteId={selectedRouteId}
          onSelectRoute={onSelectRoute}
          typeFilters={typeFilters}
          onToggleType={onToggleType}
          terminalsCount={TERMINALS.length}
          paraderosCount={paraderos.length || PARADEROS_APPROX_COUNT}
          showTerminals={showTerminals}
          showParaderos={showParaderos}
          onToggleTerminals={() => setShowTerminals((v) => !v)}
          onToggleParaderos={() => setShowParaderos((v) => !v)}
        />

        <main className="relative flex-1">
          <ConceMap
            theme={theme}
            routes={ROUTES}
            visibleRouteIds={visibleIdsAfterTypeFilter}
            selectedRouteId={selectedRouteId}
            selectedStopId={selectedStopId}
            onSelectRoute={onSelectRoute}
            onSelectStop={onSelectStop}
            flyToToken={flyToToken}
            terminals={TERMINALS}
            showTerminals={showTerminals}
            selectedTerminalId={selectedTerminalId}
            onSelectTerminal={onSelectTerminal}
            paraderos={paraderos}
            showParaderos={showParaderos && paraderos.length > 0}
            onSelectParadero={onSelectParadero}
          />

          {!sheetKind && (
            <div className="pointer-events-none absolute left-3 top-3 z-10 animate-fade-in">
              <Card className="pointer-events-auto max-w-[260px] border-border/80 backdrop-blur supports-[backdrop-filter]:bg-background/85">
                <CardHeader className="space-y-1 p-3">
                  <CardTitle className="flex items-center gap-1.5 text-xs uppercase tracking-wider text-muted-foreground">
                    <MapPin className="h-3 w-3" />
                    Concepción · Biobío
                  </CardTitle>
                  <CardDescription className="text-[12px] leading-snug text-foreground">
                    Toca una línea, paradero o terminal. Usa <Kbd>⌘</Kbd> <Kbd>K</Kbd> para
                    buscar. Activa <span className="font-medium">Paraderos OSM</span> en la
                    barra para ver los ~1.7k paraderos urbanos.
                  </CardDescription>
                </CardHeader>
              </Card>
            </div>
          )}

          <div className="pointer-events-none absolute bottom-4 left-3 z-10">
            <div className="pointer-events-auto rounded-md border bg-background/90 px-3 py-2 text-[11px] shadow-sm backdrop-blur">
              <div className="mb-1 font-medium uppercase tracking-wider text-muted-foreground">
                Leyenda
              </div>
              <div className="flex flex-col gap-1">
                {ROUTES.map((r) => (
                  <div key={r.id} className="flex items-center gap-2">
                    <span
                      className="inline-block h-[3px] w-5 rounded-full"
                      style={{ background: r.color }}
                    />
                    <span className="font-mono text-[10px] text-muted-foreground">
                      {r.code}
                    </span>
                    <span className="max-w-[160px] truncate">
                      {ROUTE_TYPES[r.type].short}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>

      <RouteDetailSheet
        open={sheetKind === 'route'}
        route={selectedRoute}
        onOpenChange={(o) => (!o ? closeSheet() : undefined)}
        onFocusRoute={onFocusRoute}
        onSelectStop={onSelectStop}
      />
      <StopDetailSheet
        open={sheetKind === 'stop'}
        stop={selectedStop}
        onOpenChange={(o) => (!o ? closeSheet() : undefined)}
        onSelectRoute={onSelectRoute}
      />
      <TerminalDetailSheet
        open={sheetKind === 'terminal'}
        terminal={selectedTerminal}
        onOpenChange={(o) => (!o ? closeSheet() : undefined)}
        onFocus={onFocusTerminal}
      />
    </div>
  );
}
