// AUTO-GENERATED by scripts/fetch-biotren.ts on 2026-05-14T18:32:06.699Z.
// Source: OpenStreetMap (Overpass API) — node operator~EFE in Biobío bbox.
// Station order is from EFE Trenes (efe.cl/biotren/servicio-y-trazado).
// Re-generate: `npm run sync:biotren`. Do not edit by hand.

import type { LatLngTuple, Stop } from '@/types/transport';

export const BIOTREN_L1_STOPS: Stop[] = [
  { id: 'osm-4455930417', name: "Hualqui", lat: -36.9805523, lng: -72.9411329, ref: 'HQ' },
  { id: 'osm-4514615375', name: "La Leonera", lat: -36.9512437, lng: -73.0131475, ref: 'ZW' },
  { id: 'osm-4514615376', name: "Manquimávida", lat: -36.9385989, lng: -73.0112978, ref: 'man' },
  { id: 'osm-4514589079', name: "Pedro Medina", lat: -36.9257187, lng: -73.0214211, ref: 'pme' },
  { id: 'osm-4514590030', name: "Chiguayante", lat: -36.9153573, lng: -73.0288408, ref: 'CV' },
  { id: 'osm-310000768', name: "Concepción", lat: -36.8301581, lng: -73.0610353, ref: 'CC' },
  { id: 'osm-332795804', name: "Lorenzo Arenas", lat: -36.8082137, lng: -73.0710622, ref: 'lor' },
  { id: 'osm-5583753385', name: "UTF Santa María", lat: -36.7838587, lng: -73.085597, ref: 'utf' },
  { id: 'osm-4514677144', name: "Los Cóndores", lat: -36.7566703, lng: -73.0916618, ref: 'con' },
  { id: 'osm-4514677093', name: "Higueras", lat: -36.7396171, lng: -73.1025529, ref: 'hig' },
  { id: 'osm-332793725', name: "El Arenal", lat: -36.7255417, lng: -73.1166534, ref: 'EZ' },
  { id: 'osm-2063360442', name: "Mercado de Talcahuano", lat: -36.7119613, lng: -73.1155382, ref: 'TH' },
];

export const BIOTREN_L2_STOPS: Stop[] = [
  { id: 'osm-4124952607', name: "Coronel", lat: -37.0246351, lng: -73.1508068, ref: 'CW' },
  { id: 'osm-4124951369', name: "Laguna Quiñenco", lat: -37.0127009, lng: -73.1580923, ref: 'lqu' },
  { id: 'osm-4124950639', name: "Cristo Redentor", lat: -36.9984065, lng: -73.1627912, ref: 'cri' },
  { id: 'osm-6329456006', name: "Huinca", lat: -36.9882322, lng: -73.1631562, ref: 'hui' },
  { id: 'osm-4124944293', name: "Los Canelos", lat: -36.9801863, lng: -73.1628369, ref: 'can' },
  { id: 'osm-4124947356', name: "Hito Galvarino", lat: -36.9537909, lng: -73.1567244, ref: 'ES' },
  { id: 'osm-4124945257', name: "Cardenal Raúl Silva Henríquez", lat: -36.8984905, lng: -73.1433861 },
  { id: 'osm-4593412639', name: "Lomas Coloradas", lat: -36.8825028, lng: -73.1395361, ref: 'LM' },
  { id: 'osm-4593443220', name: "El Parque", lat: -36.8678229, lng: -73.1359859, ref: 'par' },
  { id: 'osm-4593412640', name: "Costa Mar", lat: -36.8548032, lng: -73.1328488, ref: 'cma' },
  { id: 'osm-3369569831', name: "Alborada", lat: -36.846867, lng: -73.1309361, ref: 'SU' },
  { id: 'osm-353772399', name: "Diagonal Bío-Bío", lat: -36.8373995, lng: -73.1180569, ref: 'dia' },
  { id: 'osm-315019820', name: "Juan Pablo II", lat: -36.8384342, lng: -73.0979637, ref: 'BB' },
  { id: 'osm-310000768', name: "Concepción", lat: -36.8301581, lng: -73.0610353, ref: 'CC' },
];

// Path geometry: stations connected in order. OSM does not currently have the
// Biotrén lines as route relations, so for now we connect the dots. A future
// iteration can replace this with the actual `railway=rail` ways.
export const BIOTREN_L1_PATH: LatLngTuple[] = BIOTREN_L1_STOPS.map((s) => [s.lat, s.lng]);
export const BIOTREN_L2_PATH: LatLngTuple[] = BIOTREN_L2_STOPS.map((s) => [s.lat, s.lng]);
