// AUTO-GENERATED by scripts/generate-gtfs-concepcion.ts on 2026-05-15T20:54:36.432Z.
// Barrel — re-exports from the split files. Prefer importing from
// gtfs-stops.generated.ts directly to avoid bundling the heavy bus-routes
// chunk into your module.

export { GTFS_STOPS, GTFS_CONCEPCION_SOURCE } from './gtfs-stops.generated';
export { GTFS_BUS_ROUTES } from './gtfs-bus-routes.generated';
