// AUTO-GENERATED by scripts/fetch-wikidata.ts on 2026-05-14T23:08:27.914Z.
// Source: Wikidata SPARQL endpoint. Enrichment keyed by Wikidata Q-id for the
// Biotrén stations that have one tagged in OSM (17 stations).
// Re-generate: `npm run sync:wikidata`.

import type { WikidataEnrichment } from '@/types/transport';

export const BIOTREN_WIKIDATA: Record<string, WikidataEnrichment> = {
  'Q5843088': { openedYear:2005, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_La_Leonera_(Biotr%C3%A9n)" },
  'Q5843577': { openedYear:2001, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Manquim%C3%A1vida" },
  'Q5844121': { openedYear:2001, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Pedro_Medina" },
  'Q5841565': { openedYear:1873, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/N1228126322%2030055144%20225.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Chiguayante" },
  'Q5841708': { openedYear:2000, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Estaci%C3%B3n%20%22provisoria%22%20Concepci%C3%B3n.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Concepci%C3%B3n" },
  'Q5475772': { openedYear:2001, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Estaci%C3%B3n%20Lorenzo%20Arenas%20-%20Wikipaseo%20fotogr%C3%A1fico%20Concepci%C3%B3n%202019%20-%20%28190%29.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Lorenzo_Arenas" },
  'Q5845266': { openedYear:2005, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Estaci%C3%B3n%20Universidad%20T%C3%A9cnica%20Federico%20Santa%20Mar%C3%ADa%20-%20Wikipaseo%20fotogr%C3%A1fico%20Concepci%C3%B3n%202019%20-%20%28002%29.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Universidad_T%C3%A9cnica_Federico_Santa_Mar%C3%ADa" },
  'Q5843722': { openedYear:2005, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Estacionbiotrentalcahuano.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Mercado_de_Talcahuano" },
  'Q5788800': { openedYear:2016, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Estacion%20Intermodal%20Coronel%20Noche.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Coronel" },
  'Q24110098': { openedYear:2016, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Laguna_Qui%C3%B1enco" },
  'Q25408894': { openedYear:2016, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Cristo_Redentor" },
  'Q25408872': { openedYear:2016, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Los_Canelos" },
  'Q5843407': { openedYear:2005, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Estacion%20Lomas%20Coloradas.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Lomas_Coloradas" },
  'Q26037129': { openedYear:2017, imageUrl:"http://commons.wikimedia.org/wiki/Special:FilePath/Vista%20norte%20de%20la%20Estaci%C3%B3n%20El%20Parque%2C%20de%20L%C3%ADnea%202%20de%20Biotr%C3%A9n.jpg?width=480", wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_El_Parque" },
  'Q16492820': { openedYear:2014, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Alborada" },
  'Q5841921': { openedYear:2005, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Diagonal_Biob%C3%ADo" },
  'Q5842945': { openedYear:2005, wikipediaEs:"https://es.wikipedia.org/wiki/Estaci%C3%B3n_Juan_Pablo_II" },
};
